services:
  - docker
before_install:
  - docker build . -t rain
notifications:
    slack: substantic:FJsopazpmJ5siyjfWCW36CVj
stages:
  - test
jobs:
  include:
    - stage: test
      script: docker run rain /bin/bash -c '. $HOME/.cargo/env && cargo test -- --test-threads=1'
    - stage: test
      script: docker run -u 123 -e RAIN_TEST_BIN=/rain/target/release/rain -e RUST_TASK_TESTER=/rain/target/release/rain_task_test rain pytest -x -v --timeout=300
    - stage: test
      script: docker run rain /bin/bash -c '. $HOME/.cargo/env && utils/checks/stylecheck.sh'
